sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm run lint
script: npm run $COMMAND
env:
  matrix:
    - COMMAND='build'
after_success:
  - npm run semantic-release
branches:
  only:
    - "master"
